# 端口号
server:
  port: 8003

# mybatis配置
mybatis:
  type-aliases-package: cn.cloud.entity   #配置实体类别名
  mapper-locations:
    - classpath:mapper/**/*.xml             #mapper映射文件

# 数据库配置
spring:
  application:
    name: SpringCloud-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #数据源
    driver-class-name: org.gjt.mm.mysql.Driver          #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB03          #数据库名称
    username: root
    password: 5615123
    dbcp2:
      min-idle: 5                 #数据库连接池最小维持连接数
      initial-size: 5             #初始化连接数
      max-total: 5                #最大连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: server8003
    prefer-ip-address: true
